# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mfa', '0002_auto_20160706_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecoveryCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp_type',
            field=models.CharField(choices=[('HOTP', 'hotp'), ('TOTP', 'totp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrecoverycodes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_mfa.UserOTP'),
        ),
    ]
