# Generated by Django 4.2.30 on 2026-08-12 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_mfa', '0003_change_secret_code_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u2fkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrecoverycodes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrecoverycodes',
            name='secret_code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('totp', 'Authenticator app'), ('webauthn', 'Security key or passkey'), ('recovery_codes', 'Recovery codes')], max_length=32)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_authenticators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='authenticator',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ['totp', 'recovery_codes'])), fields=('user', 'type'), name='mfa_one_singleton_authenticator_per_user'),
        ),
    ]
