# Generated by Django 4.2.30 on 2026-08-13 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_mfa', '0005_migrate_to_authenticator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaUserHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_user_handle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
