# Generated by Django 6.1 on 2026-08-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mfa', '0009_mfa_exemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
